---
title: "Reporte Comercial"
output:
  html_document:
    toc: yes
    toc_float: yes
    collapsed: no
    number_sections: no
    toc_depth: 1

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=FALSE)
library(lubridate)
setwd("C:/Users/LBarrios/Desktop/testgithub/Lansier")
```
Informes generados por el área de análisis comercial.


```{r FIG1 setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(kableExtra)
library(tidyverse)
library(tinytex)
library(knitr)
library(readxl)
library(ggplot2)
library(lubridate)
library(colorspace)
library(RODBC)
sqlcomercial<-odbcConnect("SQLuis",uid = "sa",pwd = "Comercial.2020")
fecharcarga<-sqlQuery(sqlcomercial,"select * from Fechas_Carga")
data<-read_xlsx("C:\\Users\\LBarrios\\Desktop\\SQLDATAEXTRACTOR\\mailrdata\\datapresentacion.xlsx") #borre todo el path que decia C/USERS,etc y lo deje solo en el nombre de el archivo, asi ya no importa donde lo corra siempre y cuando este en el wd
#con los siguientes comandos se le da cierto formato a la tabla para que sea mas facil de presentar la data en una tabla
# AL PARECER PARA QUE ACTUALICE LA DATA TENGO QUE CAMBIAR ALGO DEL CODIGO SINO NO CORRE
tabla<-data %>% select(-3) %>% select(-1)
for (i in 3:8) {
  tabla[,i]<-tabla[,i]
  
}
for (i in 1:5) {
  tabla[i,1]<-substr(tabla[i,1],5,nchar(tabla[i,1])-4)
}

for (i in 6:10) {
  tabla[i,1]<-substr(tabla[i,1],5,nchar(tabla[i,1])-4)
}
for (i in 16:19) {
  tabla[i,1]<-substr(tabla[i,1],5,nchar(tabla[i,1]))
}

# He borrado los *100(multiplicado por 100) en la linea 28 y linea 75 porque ahora mis valores no estan en decimales sino enteros, revisar eso


```
# Fechas de actualización
```{r echo=FALSE , cache=FALSE}
colnames(fecharcarga)<-c("Fuente","Fecha de Actualización")
fecharcarga %>%
  kbl(booktabs = TRUE,align = "c") %>% 
  kable_styling(bootstrap_options = c("striped","hover","condensed","responsive","bordered"),
                full_width = FALSE,
                position = "left",
                font_size = 12) %>% 
  row_spec(0, bold = T, color = "white", background = "#2a4454")
 
```
# Performance por categorización
### Porcentaje de cumplimiento
```{r , echo=FALSE, fig.pos="H",cache=FALSE}

tabla %>%
  kbl(booktabs = TRUE ) %>%
  kable_styling(bootstrap_options = c("striped","hover","condensed","responsive")) %>% 
  pack_rows("RR MM Lima Azul", 1, 5,color = "blue") %>%
  pack_rows("RR MM Lima Rojo", 6, 10,color = "red") %>%
  pack_rows("RR MM Provincias", 11, 15,color = "green") %>%
  pack_rows("VENDEDORES Lima", 16, 19) %>%
  row_spec(0,bold=T, color = "white", background = "#2a4454") %>% 
  footnote(number=c("Los valores estan en porcentajes")) %>% 
  column_spec(3, color = "black",bold=T, background = ifelse(tabla$Total > 100, "green", ifelse(tabla$Total<80,"red","yellow")))
   
        
 

```



```{r dataventas setup, include=FALSE, cache=FALSE}
dataventas<-read_xlsx("C:\\Users\\LBarrios\\Desktop\\SQLDATAEXTRACTOR\\mailrdata\\datapresentacionventas.xlsx") #borre todo el path que decia C/USERS,etc y lo deje solo en el nombre de el archivo, asi ya no importa donde lo corra siempre y cuando este en el wd
#con los siguientes comandos se le da cierto formato a la tabla para que sea mas facil de presentar la data en una tabla
# AL PARECER PARA QUE ACTUALICE LA DATA TENGO QUE CAMBIAR ALGO DEL CODIGO SINO NO CORRE
tablaventas<-dataventas %>% select(-3) %>% select(-1)
for (i in 3:8) {
  tablaventas[,i]<-round(tablaventas[,i],0)
  tablaventas[,i]<-lapply(tablaventas[,i],format,big.mark=",")
}
for (i in 1:5) {
  tablaventas[i,1]<-substr(tablaventas[i,1],5,nchar(tablaventas[i,1])-4)
}

for (i in 6:10) {
  tablaventas[i,1]<-substr(tablaventas[i,1],5,nchar(tablaventas[i,1])-4)
}
for (i in 16:19) {
  tablaventas[i,1]<-substr(tablaventas[i,1],5,nchar(tablaventas[i,1]))
}

# He borrado los *100(multiplicado por 100) en la linea 28 y linea 75 porque ahora mis valores no estan en decimales sino enteros, revisar eso
```

### Ventas en soles

```{r tablaventas , echo=FALSE, fig.pos="H",cache=FALSE}

tablaventas %>%
  kbl(booktabs = TRUE) %>%
  kable_styling(bootstrap_options = c("striped","hover","condensed","responsive")) %>% 
  pack_rows("RR MM Lima Azul", 1, 5,color = "blue") %>%
  pack_rows("RR MM Lima Rojo", 6, 10,color = "red") %>%
  pack_rows("RR MM Provincias", 11, 15,color = "green") %>%
  pack_rows("VENDEDORES Lima", 16, 19) %>%
  row_spec(0,bold=T, color = "white", background = "#2a4454") %>%
  column_spec(3, color = "black",bold=T, background = ifelse(tabla$Total > 100, "green", ifelse(tabla$Total<80,"red","yellow"))) %>% 
  footnote(number = c("Los valores estan en soles"))
```


# Cumplimiento por zona
```{r echo=FALSE, fig.pos="H", cache=FALSE}
#donde dice ifelse antes iba el valor fijo segun la semana, ya sea 20,40,70 o 100, ahora ya esta automatico en funcion a la fecha que se corre.
data %>%
  mutate(Total=Total) %>% 
  ggplot(aes(x=reorder(Nombre,Total),y=Total))+
  geom_bar(stat = "identity",color="black",fill="steelblue")+
  coord_flip()+labs(x="",y="%")+
          theme_minimal()+
  geom_text(aes(label=Total), hjust=-0.15, size=2.6)+
  geom_hline(yintercept =ifelse(day(today())>23,100,ifelse(day(today())>16,70,ifelse(day(today())>9,40,ifelse(day(today())>3,20,100)))) ,linetype="dotted",color="black")+
  geom_text(aes(0,
                ifelse(day(today())>23,100,ifelse(day(today())>16,70,ifelse(day(today())>9,40,ifelse(day(today())>3,20,100)))),
                label = ifelse(day(today())>23,100,ifelse(day(today())>16,70,ifelse(day(today())>9,40,ifelse(day(today())>3,20,100)))),
                vjust = 0),
            size=3,
            colour="black"
            )
```

